version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname?schema=public?connect_timeout=300
    command: /bin/sh -c "npx prisma generate --schema=./src/prisma/schema.prisma && npx prisma migrate dev --name init --schema=./src/prisma/schema.prisma && yarn dev"

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password