directive @auth on FIELD_DEFINITION | OBJECT
type Task {
    id: Int!
    title: String!
    completed: Boolean!
    createdAt: String!
    updatedAt: String!
    user: User!
}

type Query {
    getTasks: [Task!]! @auth
    getTask(id: Int!): Task! @auth
    getTasksByUser(userId: Int!): [Task!]! @auth
}

type Mutation {
    createTask(title: String!, userId: Int!): Task! @auth
    updateTask(id: Int!, title: String, completed: Boolean): Task! @auth
    deleteTask(id: Int!): Boolean! @auth
}