directive @auth on FIELD_DEFINITION | OBJECT
type User {
  	id: Int!
  	email: String!
  	name: String
	password: String!
	createdAt: String!
	updatedAt: String!
	tasks: [Task]
}

type Query {
    users: [User!]! @auth
    user(id: Int!): User @auth
}

type Mutation {
	createUser(email: String!, name: String!, password: String!): User! @auth
	updateUser(id: Int!, email: String, name: String, password: String): User! @auth
  	deleteUser(id: Int!): Boolean! @auth
	login(email: String!, password: String!): String!
}
